# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8efc6d8d909aa8787e6042ac57e736120e7e522403bd6eaa292cd567d5fe8d7e55bfe63f36e153fb3da597f0a688b3a3b2bf9ac1a0bab983cedfe608cb8201e

test:
  secret_key_base: b8271e40d6aed9ecc86c96697b4fa5f8b956bd4ccc0e58fda8348c94fd5ebdbf823af8ed7ccb83394bb4271d83aae19213b36d10977cf53c83ace80261f91a27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
